// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"API_Gateway/api/internal/handler/admin"
	"API_Gateway/api/internal/svc"
	"net/http"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: admin.AdminLoginHandler(serverCtx),
			},
		},
	)
}
